import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const dinCondensed = localFont({
  src: [
    {
      path: "../../public/fonts/Fonts_DINCondensed-Bold.ttf",
      weight: "700",
      style: "bold",
    },
    {
      path: "../../public/fonts/Fonts_DinCond-Regular Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-din-condensed",
});

const gadugi = localFont({
  src: "../../public/fonts/gadugi.ttf",
  variable: "--font-gadugi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gadugi.variable} ${dinCondensed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
